### ISSUE TITLE
Need support for Minecraft v1.21.1

### ISSUE THREAD

**Issue by bearaujus** [jodeks-datapacks/No-Spawn-Chunk-Forceload#1]
Need help to update this mod to support Minecraft v1.21.1, thank you!

**Comment by Jodekq** [comment]
Im so sorry I somehow did not see the issue.
I will upload a version for 1.21.1

**Comment by Jodekq** [comment]
Heres the updated mod: https://modrinth.com/datapack/spawnchunks-disabled/version/v.3.0.0+mod
